create table offers (
  id integer primary key generated by default as identity,
  title text not null,
  slug text not null unique,
  body text not null,
  inserted_at timestamp(0) not null default (now() at time zone 'utc'),
  updated_at timestamp(0) not null default (now() at time zone 'utc')
);
