[psql]
  dbname = "shigoto_dev"
  user = "postgres"
  password = "postgres"
  blacklist = ["schema_migrations"]
  host = "localhost"
  sslmode = "disable"

[auto-columns]
  created = "inserted_at"
  updated = "updated_at"
