// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testOffers(t *testing.T) {
	t.Parallel()

	query := Offers()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testOffersDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Offer{}
	if err = randomize.Struct(seed, o, offerDBTypes, true, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Offers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOffersQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Offer{}
	if err = randomize.Struct(seed, o, offerDBTypes, true, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Offers().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Offers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOffersSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Offer{}
	if err = randomize.Struct(seed, o, offerDBTypes, true, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OfferSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Offers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOffersExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Offer{}
	if err = randomize.Struct(seed, o, offerDBTypes, true, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := OfferExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Offer exists: %s", err)
	}
	if !e {
		t.Errorf("Expected OfferExists to return true, but got false.")
	}
}

func testOffersFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Offer{}
	if err = randomize.Struct(seed, o, offerDBTypes, true, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	offerFound, err := FindOffer(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if offerFound == nil {
		t.Error("want a record, got nil")
	}
}

func testOffersBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Offer{}
	if err = randomize.Struct(seed, o, offerDBTypes, true, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Offers().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testOffersOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Offer{}
	if err = randomize.Struct(seed, o, offerDBTypes, true, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Offers().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testOffersAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	offerOne := &Offer{}
	offerTwo := &Offer{}
	if err = randomize.Struct(seed, offerOne, offerDBTypes, false, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}
	if err = randomize.Struct(seed, offerTwo, offerDBTypes, false, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = offerOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = offerTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Offers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testOffersCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	offerOne := &Offer{}
	offerTwo := &Offer{}
	if err = randomize.Struct(seed, offerOne, offerDBTypes, false, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}
	if err = randomize.Struct(seed, offerTwo, offerDBTypes, false, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = offerOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = offerTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Offers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func offerBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Offer) error {
	*o = Offer{}
	return nil
}

func offerAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Offer) error {
	*o = Offer{}
	return nil
}

func offerAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Offer) error {
	*o = Offer{}
	return nil
}

func offerBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Offer) error {
	*o = Offer{}
	return nil
}

func offerAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Offer) error {
	*o = Offer{}
	return nil
}

func offerBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Offer) error {
	*o = Offer{}
	return nil
}

func offerAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Offer) error {
	*o = Offer{}
	return nil
}

func offerBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Offer) error {
	*o = Offer{}
	return nil
}

func offerAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Offer) error {
	*o = Offer{}
	return nil
}

func testOffersHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Offer{}
	o := &Offer{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, offerDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Offer object: %s", err)
	}

	AddOfferHook(boil.BeforeInsertHook, offerBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	offerBeforeInsertHooks = []OfferHook{}

	AddOfferHook(boil.AfterInsertHook, offerAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	offerAfterInsertHooks = []OfferHook{}

	AddOfferHook(boil.AfterSelectHook, offerAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	offerAfterSelectHooks = []OfferHook{}

	AddOfferHook(boil.BeforeUpdateHook, offerBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	offerBeforeUpdateHooks = []OfferHook{}

	AddOfferHook(boil.AfterUpdateHook, offerAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	offerAfterUpdateHooks = []OfferHook{}

	AddOfferHook(boil.BeforeDeleteHook, offerBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	offerBeforeDeleteHooks = []OfferHook{}

	AddOfferHook(boil.AfterDeleteHook, offerAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	offerAfterDeleteHooks = []OfferHook{}

	AddOfferHook(boil.BeforeUpsertHook, offerBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	offerBeforeUpsertHooks = []OfferHook{}

	AddOfferHook(boil.AfterUpsertHook, offerAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	offerAfterUpsertHooks = []OfferHook{}
}

func testOffersInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Offer{}
	if err = randomize.Struct(seed, o, offerDBTypes, true, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Offers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOffersInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Offer{}
	if err = randomize.Struct(seed, o, offerDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(offerColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Offers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOffersReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Offer{}
	if err = randomize.Struct(seed, o, offerDBTypes, true, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOffersReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Offer{}
	if err = randomize.Struct(seed, o, offerDBTypes, true, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OfferSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOffersSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Offer{}
	if err = randomize.Struct(seed, o, offerDBTypes, true, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Offers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	offerDBTypes = map[string]string{`ID`: `integer`, `Title`: `text`, `Slug`: `text`, `Body`: `text`, `InsertedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`}
	_            = bytes.MinRead
)

func testOffersUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(offerPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(offerAllColumns) == len(offerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Offer{}
	if err = randomize.Struct(seed, o, offerDBTypes, true, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Offers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, offerDBTypes, true, offerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testOffersSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(offerAllColumns) == len(offerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Offer{}
	if err = randomize.Struct(seed, o, offerDBTypes, true, offerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Offers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, offerDBTypes, true, offerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(offerAllColumns, offerPrimaryKeyColumns) {
		fields = offerAllColumns
	} else {
		fields = strmangle.SetComplement(
			offerAllColumns,
			offerPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := OfferSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testOffersUpsert(t *testing.T) {
	t.Parallel()

	if len(offerAllColumns) == len(offerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Offer{}
	if err = randomize.Struct(seed, &o, offerDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Offer: %s", err)
	}

	count, err := Offers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, offerDBTypes, false, offerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Offer struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Offer: %s", err)
	}

	count, err = Offers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
